name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Sprawdzenie repo
      uses: actions/checkout@v2

    - name: Zbuduj obraz Docker
      run: docker build -t goldarian/lab12:latest .

    - name: Zaloguj do DockerHub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Przepchnij obraz Docker
      run: docker push nadzeyas/lab14:latest
